forum/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='forum'),
    path('ask', views.ask, name='ask'),
    path('Question', views.question, name='question')
]

mainApp/urls.py
from django.urls import path
from . import views
from .userverfiy import fn_verify_token, forgot_password, change_password

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('ActivateUser', fn_verify_token),
    path('profile', views.profile, name='user_profile'),
    path('ForgotPassword', forgot_password, name='forgotpassword'),
    path('ChangePassword', change_password),
]

testProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls, name='index'),
    path('', include('mainApp.urls')),
    path('courses/', include('courses.urls')),
    path('forum/', include('forum.urls')),
    path('squad/', include('squad.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_delete


# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Additionals
    profile_pic = models.ImageField(upload_to='profile_pics', default=None, blank=True)

    def __str__(self):
        return self.user.username


User._meta.get_field('email')._unique = True


class UserToken(models.Model):
    token = models.CharField(max_length=37)
    link = models.URLField(blank=True)
    userId = models.IntegerField()


class PasswordToken(models.Model):
    token = models.CharField(max_length=37)
    link = models.URLField(blank=True)
    userId = models.IntegerField()


@receiver(post_delete, sender=UserProfileInfo)
def submission_delete(sender, instance, **kwargs):
    instance.profile_pic.delete(False)

mainApp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password',
        ]

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = [
            'profile_pic',
        ]

mainApp/views.py
from django.shortcuts import render
from .models import UserProfileInfo
from .forms import UserProfileInfoForm, UserForm

#
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .userverfiy import fn_generate_token
from django.core.mail import send_mail


# Create your views here.
def index(req):
    return render(req, 'index.html')


def register(req):
    registered = False

    if req.method == 'POST':
        user_form = UserForm(data=req.POST)
        profile_form = UserProfileInfoForm(data=req.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.is_active = False
            user.save()
            user_profile = profile_form.save(commit=False)
            user_profile.user = user
            if 'profile_pic' in req.FILES:
                user_profile.profile_pic = req.FILES['profile_pic']
            user_profile.save()
            registered = True

            send_mail(
                'Email Confirmation - COL',
                'Click the link to confirm \n {}'.format(fn_generate_token(user.id)),
                'milanmuhammed1@gmail.com',
                [req.POST['email']],
                fail_silently=False,
            )

            return render(req,'confirm.html',{
                'email': str(user.email),
            })
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(req, 'register.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    })


def user_login(req):
    if req.method == 'POST':
        username = req.POST['username']
        password = req.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(req, user)
                return HttpResponseRedirect(reverse('user_profile'))
            else:
                return HttpResponse('User is not Active')
        else:
            return HttpResponse('Inavlid login Credential. Go back to try again')
    else:
        return render(req, 'login.html')


@login_required
def user_logout(req):
    logout(req)
    return HttpResponseRedirect(reverse('index'))

@login_required
def profile(req):
    if 'profile_pic' in req.FILES:
        userProfile = UserProfileInfo.objects.get(user=req.user)
        userProfile.profile_pic = req.FILES['profile_pic']
        userProfile.save()

    userProfile = UserProfileInfo.objects.get(user=req.user)
    try:
        img = userProfile.profile_pic
    except:
        img = None
    return render(req, 'profile.html', {
        'profile_pic': img,
    })
    

mainApp/templates/changepass.html
{% extends 'base.html' %}
{% block title %}Forgot{% endblock %}
{% block content %}

<div class="container">
	<div class="jumbotron">
		<form method="POST">
			{% csrf_token %}
			<p>
				<label for="password">New Password : </label>
				<input type="password" name="newPass">
				<input type="hidden" name='userId' value="{{ userId }}">
			</p>
			<input type="submit" name="">
		</form>
	</div>
</div>

{% endblock %}

mainApp/templates/confirm.html
{% extends 'base.html' %}
{% block title %}Confirm your Email{% endblock %}
{% block content %}

<div class="container">
    <div class="jumbotron" style="text-align: center;">
        <h1 class="display-2">Thank You For Registering On Col.</h1>
        <h3> We have send an email to {{email}} with a confirmation link. Click on it to confirm your account.</h3>
        <p>Without confirming your account you many not be able to login.</p>
    </div>
</div>

{% endblock %}

mainApp/templates/forgot.html
{% extends 'base.html' %}
{% block title %}Forgot{% endblock %}
{% block content %}

<div class="container">
	<dir class="jumbotron">
		<form method="POST">
			{% csrf_token %}
			<p>
				<label for="email">Email : </label>
				<input type="email" name="email">
			</p>
			<input type="submit" name="">
		</form>
	</dir>
</div>

{% endblock %}

mainApp/templates/login.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<style>

    td{
        padding: 10px;
    }

    #login-btn{
        color: white;
        background-color: rgb(57, 116, 226);
        border: none;
        padding: 5px 15px;
        border-radius: 3px;
    }
    #login-btn:hover{
        background-color: rgb(72, 72, 252);
    }

</style>

{% if user.is_authenticated %}
<h1>Thankyou for logging in</h1>
{% else %}
<div class="container jumbotron">
    <form action="{% url 'user_login' %}" method="POST">
        {% csrf_token %}
        <div>
        <table style="margin: auto;">
            <tr>
                <td> <label for="username">User name:</label></td>
                <td> <input type="text" name="username" placeholder="Enter username"></td>
            </tr>
            <tr>
                <td> <label for="password">Password:</label></td>
                <td> <input type="password" name="password" placeholder="password"></td>
            </tr>
            <tr>
                <td><a href="{% url 'forgotpassword' %}">forgot password?</a></td>
            </tr>
            <tr>
                <td><input type="submit" name="" value="Login" id="login-btn"></td>
            </tr>
        </table>


        </div>
    </form>
</div>
{% endif %}


{% endblock %}

mainApp/templates/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}
{% block content %}

<style>
    .image-cropper {
        width: 150px;
        height: 150px;
        position: relative;
        overflow: hidden;
        border-radius: 50%;
    }

    .img {
        display: inline;
        margin: 0 auto;
        height: 100%;
        width: auto;
    }
</style>


<div class="container">
    <div class="jumbotron">

        <div class="row">
            <div class="col col-lg-6" style="font-size: 1.689em;">
                <h1 class="display-2">Profile</h1>
                <p>User : <b>{{ user.username }}</b></p>
                <p>Email : <b>{{ user.email }}</b></p>
            </div>
            <div class="col col-lg-4" style="margin-right: 0; margin-left: auto;">
                {% if profile_pic %}
                <div class="image-cropper">
                    <img src="{{ profile_pic.url }}" class="img" >
                </div>
                {% else %}
                <p>no profile pic</p>
                {% endif %}
                <br>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="pic">Change Profile Pic : </label>
                    <input type="file" name="profile_pic" id="pic" accept="image/*"><br>
                    <input type="submit" name="" value="Upload" class="btn btn-primary">
                </form>
            </div>

        </div>
        <br><br>
        <a href="{% url 'forgotpassword' %}">Change Password</a>
    </div>
</div>


{% endblock %}

mainApp/templates/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}


<style>
    td{
        padding: 7px 0;
    }
</style>


<div class="container" style="margin-left: auto;">
    {% if user.is_authenticated %}
    <h1>Thank You for registering</h1>
    {% else %}
    <h1 style="text-align: center;">Register here</h1>
    <h2 style="text-align: center;">Fill in the below form:</h2>
    <form method="POST" enctype="multipart/form-data" style="text-align: center;" class="jumbotron ml-auto">
        <input type="hidden" name="csrfmiddlewaretoken"
            value="ahemjqpnbGxXxdYNLKI5tYt2UInPOVOp20cJK8CIT1vOTJBxJkeBObK7REiPCiB1">
        
        <table style="margin: auto; text-align: left;">
            {% csrf_token %}
            <tr>
                <td><label for="id_username">Username:</label></td>
                <td> <input type="text" name="username" maxlength="150" required id="id_username"> <span class="helptext"></span></td>
            </tr>
            <tr>
                <td><label for="id_email">Email address:</label> </td>
                <td><input type="email" name="email" maxlength="254" id="id_email"></td>
            </tr>
            <tr>
                <td><label for="id_password">Password:</label> </td>
                <td><input type="password" name="password" required id="id_password"></td>
            </tr>
            
        </table>

        <br>
        <p><input type="file" name="profile_pic" accept="image/*"
                id="id_profile_pic"></p>
                {% if user_form.errors %}
                {% for field in user_form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in user_form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
        <button type="submit" class="btn-lg" style="border-radius: 50px;">Submit</button>
    </form>
    {% endif %}
</div>


{% endblock %}

mainApp/templates/thankyou.html
{% extends 'base.html' %}
{% block title %}Confirm your Email{% endblock %}
{% block content %}

<div class="container">
    <div class="jumbotron" style="text-align: center;">
        <h1 class="display-2">Your Account Has Been Confirmed.</h1>
        <h3>Login to your Account and Enroll in a course.</h3>
        <a class="display-1" href="{% url 'user_login' %}">Login</a>
    </div>
</div>

{% endblock %}